# GENERATED BY COMPOSE2NIX (and then modified...)
# Komodo runs my docker stack. Too lazy to convert everything to oci-containers right now
# Komodo-core runs within an oci-container controlled by systemd
# Komodo-periphery also runs within an oci-container -- will be updated soon
{ ... }:
{
  flake.modules.nixos.komodo-core =
    { lib, pkgs, config, ... }:
    let
      coreVersion = "2.1.2";
      postgresVersion = "17-0.107.0";
      ferretVersion = "2.7.0";

      databaseDir = "/opt/databases/komodo";
    in
    {
      # Will pull the komodo env file from secrets to pass to containers
      sops.secrets.komodo = {
        format = "dotenv";
        sopsFile = ../../secrets/komodo.env;
      };
      
      virtualisation.oci-containers.backend = "docker";
      # Containers
      virtualisation.oci-containers.containers."komodo-core" = {
        image = "ghcr.io/moghtech/komodo-core:${coreVersion}";
        environmentFiles = [ config.sops.secrets.komodo.path ];
        volumes = [
          "komodo-repo-cache:/repo-cache:rw"
          "komodo-keys:/config/keys"
        ];
        ports = [
          "9120:9120/tcp"
        ];
        labels = {
          "komodo.skip" = "";
        };
        dependsOn = [
          "komodo-ferretdb"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=komodo-core"
          "--network=swarmnet"
          "--network=komodo"
        ];
      };
      systemd.services."docker-komodo-core" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
          RestartMaxDelaySec = lib.mkOverride 90 "1m";
          RestartSec = lib.mkOverride 90 "100ms";
          RestartSteps = lib.mkOverride 90 9;
        };
        after = [
          "docker-network-komodo.service"
          "docker-volume-komodo-repo-cache.service"
          "docker-volume-komodo-keys.service"
        ];
        requires = [
          "docker-network-komodo.service"
          "docker-volume-komodo-repo-cache.service"
          "docker-volume-komodo-keys.service"
        ];
        partOf = [
          "docker-compose-komodo-root.target"
        ];
        wantedBy = [
          "docker-compose-komodo-root.target"
        ];
      };
      virtualisation.oci-containers.containers."komodo-ferretdb" = {
        image = "ghcr.io/ferretdb/ferretdb:${ferretVersion}";
        environmentFiles = [ config.sops.secrets.komodo.path ];
        labels = {
          "komodo.skip" = "";
        };
        dependsOn = [
          "komodo-postgres"
        ];
        volumes = [
          "komodo-ferretdb-state:/state"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=komodo-ferretdb"
          "--network=komodo"
        ];
      };
      systemd.services."docker-komodo-ferretdb" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
          RestartMaxDelaySec = lib.mkOverride 90 "1m";
          RestartSec = lib.mkOverride 90 "100ms";
          RestartSteps = lib.mkOverride 90 9;
        };
        after = [
          "docker-network-komodo.service"
        ];
        requires = [
          "docker-network-komodo.service"
        ];
        partOf = [
          "docker-compose-komodo-root.target"
        ];
        wantedBy = [
          "docker-compose-komodo-root.target"
        ];
      };
      virtualisation.oci-containers.containers."komodo-postgres" = {
        image = "ghcr.io/ferretdb/postgres-documentdb:${postgresVersion}-ferretdb-${ferretVersion}";
        environmentFiles = [ config.sops.secrets.komodo.path ];
        volumes = [
          "${databaseDir}:/var/lib/postgresql/data:rw"
        ];
        labels = {
          "komodo.skip" = "";
        };
        log-driver = "journald";
        extraOptions = [
          "--network-alias=komodo-postgres"
          "--network=komodo"
        ];
      };
      systemd.services."docker-komodo-postgres" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
          RestartMaxDelaySec = lib.mkOverride 90 "1m";
          RestartSec = lib.mkOverride 90 "100ms";
          RestartSteps = lib.mkOverride 90 9;
        };
        after = [
          "docker-network-komodo.service"
        ];
        requires = [
          "docker-network-komodo.service"
        ];
        partOf = [
          "docker-compose-komodo-root.target"
        ];
        wantedBy = [
          "docker-compose-komodo-root.target"
        ];
      };

      # Networks
      systemd.services."docker-network-komodo" = {
        path = [ pkgs.docker ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "docker network rm -f komodo";
        };
        script = ''
          docker network inspect komodo || docker network create komodo
        '';
        partOf = [ "docker-compose-komodo-root.target" ];
        wantedBy = [ "docker-compose-komodo-root.target" ];
      };

      # Volumes
      systemd.services."docker-volume-komodo-repo-cache" = {
        path = [ pkgs.docker ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          docker volume inspect komodo-repo-cache || docker volume create komodo-repo-cache
        '';
        partOf = [ "docker-compose-komodo-root.target" ];
        wantedBy = [ "docker-compose-komodo-root.target" ];
      };
      systemd.services."docker-volume-komodo-keys" = {
        path = [ pkgs.docker ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          docker volume inspect komodo-keys || docker volume create komodo-keys
        '';
        partOf = [ "docker-compose-komodo-root.target" ];
        wantedBy = [ "docker-compose-komodo-root.target" ];
      };
      systemd.services."docker-volume-komodo-ferretdb-state" = {
        path = [ pkgs.docker ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          docker volume inspect komodo-ferretdb-state || docker volume create komodo-ferretdb-state
        '';
        partOf = [ "docker-compose-komodo-root.target" ];
        wantedBy = [ "docker-compose-komodo-root.target" ];
      };

      # Root service
      # When started, this will automatically create all resources and start
      # the containers. When stopped, this will teardown all resources.
      systemd.targets."docker-compose-komodo-root" = {
        unitConfig = {
          Description = "Root target generated by compose2nix.";
        };
        wantedBy = [ "multi-user.target" ];
      };
    };
}
