# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  inputs,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    inputs.disko.nixosModules.disko
    ./disko.nix
    ./networking.nix
  ];

  # Rename builtin-speaker device
#  services.pipewire.wireplumber.extraConfig = {
#    "device-rename" = {
#      "monitor.alsa.rules" = [
#        {
#          matches = [
#            {
#              "node.name" = "alsa_output.pci-0000_c4_00.6.analog-stereo";
#            }
#          ];
#          actions = {
#            update-props = {
#              "node.description" = "PC Speakers";
#            };
#          };
#        }
#      ];
#    };
#  };

  # Logitech peripherals
  hardware.logitech.wireless.enable = true;
  hardware.logitech.wireless.enableGraphical = true;

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  hardware = {
    graphics.enable = true;
    bluetooth.enable = true;
  };

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [
    "pinctrl_icelake"           # GPIO pin‑mux for Tiger‑Lake
    "8250_dw"                     # UART that talks to the Embedded Controller
    "intel_lpss"
    "intel_lpss_pci"              # LPSS I²C controller (pulls in intel_lpss)
    "surface_gpe"                 # wakes the EC so the next two can probe
    "surface_hotplug"             # enumerates devices on the Surface bus
    "surface_aggregator_registry"
    "surface_aggregator_hub"
    "surface_aggregator"
    "surface_hid_core"
    "surface_hid"
    "surface_kbd"
  ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Pinned kernel version
  boot.kernelPackages = pkgs.linuxPackages_6_18;
  # System76 CPU Scheduler
  # services.system76-scheduler.enable = true;
  services.upower.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
