userpass:
    taylor: ENC[AES256_GCM,data:H1pUhGZ2ueasipLRfcqi+56HYnN3pq+OVWSYc22HKP1jV3Sei7v3dLEFGpxAVF/f8Mxrs7qCUriN5u1BPQfbjZVe5bSnuQ+83Q==,iv:tMxrCcQG5fJpbX3YSNteAhtftBG3YxIYqr3WwgnHf6w=,tag:GDGcFqIKPAS9LGKHy488+A==,type:str]
    sshkey: ENC[AES256_GCM,data:Eo26kowm3i/2zLjd4kfTt99E6oANn85bbHcYdhFy9Ogy7hpf8tFL8uSvfdNF0SupHnyJFHXKpRGB4Mvt1+cx6y3mltKLGVhpKnW9DNjiFF3mYbVQn0EHHfauWK4zitNPSrPgnmXX,iv:rwVZbR92mp5+3qa6M0QtXuT6IPu/kj61WMqhDURgap0=,tag:InGB4GEpq4LBZh9BEF3r2g==,type:str]
backblaze:
    keyID: ENC[AES256_GCM,data:nWkA8TpW4HK4PSWQO6bLAwnQ8dkuPYeW7g==,iv:nzBLF1H8pXrm8wsx9h+nqX3zLkStbX++Uy/QCZ1ZSMI=,tag:pzzF1GTXREwnXLf0EZwGBg==,type:str]
    applicationKey: ENC[AES256_GCM,data:B8AOGyFOAo8EUfO0B/jdPoXx9nMfQo0kBmooS4vTtA==,iv:n0jdVnHO43WDwKsoliOSrKB5Cn1i4gxlxfaS4KZU5po=,tag:E6vp/veJxHDwqx7EW5RopQ==,type:str]
    repository: ENC[AES256_GCM,data:decTk0417VDCOnNdhzYFOg6jF0gqIAzdceuHPZzZiHVKit00/uxfSlSQ+0kcsvA=,iv:KESw6Yj4oTaDZzWgrkgkA9sfoERNMr1WmQsCTXIKXEU=,tag:5VO9KKPVg0oLOnekG0+msA==,type:str]
beszel:
    sshKey: ENC[AES256_GCM,data:SrSbhS1mi5SlH7i08fEJhMogqNbHqDHQ4fL48QUTyXFKMJKkSJAxfQDCY+cbHmDxsJZEwK02B+bZ0NnM9GFbba0CD2Rzbw6gUx85YCpwG70=,iv:dJG/8w4IHzesBDMgSzLCeANyKQXt29Ew2xyswtoc3FM=,tag:iRLa8pyWhQjSJGZlYCLKZg==,type:str]
    universalToken: ENC[AES256_GCM,data:EvEjbUhpg5k2qJqpdyk3dmiUTJfV5RyeLUf1owcbxCf9v8xN,iv:NspaoNMnWXxku+Q0w+oLU4injKpIk7T/ns2mdIFKmkk=,tag:wHoB3tn8A06wMLt3dfVASQ==,type:str]
cachemover:
    pass: ENC[AES256_GCM,data:FlbW7HtnAQ==,iv:wb/Z7P8I0bCWNAEf/6ikkkHY3DHhEL0egXtFoYU9mv4=,tag:V5Ke+B/M51ofLkvy3qZw6A==,type:str]
    healthchecks: ENC[AES256_GCM,data:WjtrzBS1tFiyMDc+2atLqIDbyITLU7WKm8fZOWY77KUgMvqxJ6BCxF0kz+Jzhg0sKbjKFQtS2RALyfmjde0fFwLFTxQ5EEixZw==,iv:AZMWqMfYTg22vRg9YgVav4lQB4AtkRzKFRqtHUmYkaI=,tag:o5U2k3mBriZHmNQE64bDlg==,type:str]
    apikey: ENC[AES256_GCM,data:g9P24ZZs3mVyTsVTWKVpOqw9Tnw+XzJsKq05nw7gsZ/eYSMtzsH+Qvh5pIt97BxE8r19+3m6+S9PpMMZROyCwg==,iv:tc229JH+LsPn4REJ4syWtdSGFjRDCMJHFaoP5PMMVWI=,tag:ly+reSlunw+1t/b3e+35xg==,type:str]
    discordurl: ENC[AES256_GCM,data:8XIMrZw0jJ7trUrN8DVLkomn4sXA23pLlFIQQr1MDXYl53utV691Bj/WleIZU58mMuRhSIfqhIj3Qa0A4/Eg7rCbpGzFZuLTS4TbpoM0TEWaM3URF+rpgRN+o3uRrvQiTZQ=,iv:ODth9BBMRjdTiPl++FsnSwWCwMkTT31zSSNDQbMRCWo=,tag:Nb9Qdp9v1QpAF6uBvIzBtg==,type:str]
restic:
    repokey: ENC[AES256_GCM,data:CEgwLBYiMLBoi6OZBXlzfe2G3UUzopC5fCuzjuFUgyE=,iv:BsTRwxGExpG8i/cahNMLBuG4CfnrdZLlghv5hUwlSFI=,tag:/8OEUi84KXIwpSod8RhKDg==,type:str]
snapraid:
    healthchecks: ENC[AES256_GCM,data:lZVlP2JkRUnV+Q1Xx8MpnvOptrWayYGYlL0PfSqvt0OxGue5TxOus6nr9OVbtzcK9W9oTiWanZcYhTRRx1c3x7wtbU3YVV9bQQ==,iv:pUxJJuzCxlbQi6OzJLYLCn4M3pO7GfErwjJgboqRIlw=,tag:Rro2FGI1BZhPUiSxDHU5iA==,type:str]
renovate:
    github_key: ENC[AES256_GCM,data:qZ2Yp/DGH8A1TuncbMVMf2B0xoIyBpGJ55qppkEykY62enzworZ2lx9XE7LAr07QIBMJuyhgtKqqR3CpLoWoMuXu/2oGI/Z+oy9ki7YGFDiBq/CYb5gQEkZJcxny,iv:NM3nrXKLoWCsf+AKJYy01pBsFIjgD6uv1ZhyjPLp3yE=,tag:DuiA16V42ycnuxGkqwMQZA==,type:str]
    renovate_key: ENC[AES256_GCM,data:pfeZewpUCdprwUUe9FMLa7eF7ogjIUnJzqYjOfjKIcPujyljQr1TuA==,iv:PMLrHqkqG9xXQf5fUbErZ9dQDvgbyuFxQVRFGGB/wKg=,tag:CteXVdmvKHB3FvUPuKinFw==,type:str]
ups:
    notifyurl: ENC[AES256_GCM,data:hqVwUwGbCe+sXdjcmmEY2MRb9rs42boS9vaiZnlc/VM1bEwjH4OqpqZzh1uDhCNJohhQW27sHiWLZhoe7r80bvWgIwtrpZT5SzwNzHJYpQOznZmHshVpMqbEj9AaX0s77zsFfJLaydvhxVqzt2MjuBNG44hPv55mYA==,iv:Z209zesFABBmloir6SSjsEZmBSjAQIzy4eNvvdkEezc=,tag:t1iiiLQrkpNtyhTR2Ufjow==,type:str]
    adminpass: ENC[AES256_GCM,data:pmxtJUjWpqmDcRZdpPjSxhrqlU482HX4yjE=,iv:9FbgFyNNKWdgOOQUQOpbSoOl+c8A79FIzAvgzHLNPZA=,tag:g0Ku0DckGWKuSJ2EcBDmZw==,type:str]
    guestpass: ENC[AES256_GCM,data:xUJWj4x6M7Tu2C8otqqXoxWflg==,iv:qjrUotXSqe6bkf1QNlEAWRuwf6cf866KI46LDHu9x40=,tag:hDG5nos0HBPNGh9UgJZJTA==,type:str]
syncthing:
    cert: ENC[AES256_GCM,data:+Fg1BRCX+fxm3XX82ZuKq+7J2IGLWVTqc5jFlJJsvxPetRf+D2tKL/sbzVHXPh78QT5VkBYk9gsodXd5yOTLv6q0JF1UdEGqs/mCtnR1taPMgmG6p8hgoSah7kvBvDWZQZ/lNcnlNU2MbFvG1WLVxb97tWqYrBwAObVGxAvDITKgEFHNizIucQuYyUax6Fsa/8L3kVzaG+ijpcstZQJY4sNamngRWzK3XxXV8YkAsBiU8epIuMQH26rOn4b44lEv65/7yR5VeJyQMh5+RfH/nC7ICS2ShYOhxhrRkBhRtBlcS7QLXokVxF+9GV95CiOb2CgQuU/ZB6PGO71EdcUEMgH0NUAeF4lQcuUyE/daHZcH4UcBmNNJyTsOpe1lUuwObk2+KAmLh2IVMzZGy6DRlu4RGZmoUxvGin3veXwyHotKrUK69QStKmU2ca7YLYURBOju45t9YtbB2mFYGQGor/C79SHzKth1e/AXuJPhofBusxXla052bAVS1nOQBv1xQoC8ynC9EJJ9h9dPZYsCR5n0iTZEjGkp0bn1eB95nFvY/wh+hvRg7ckHVFuzOJSI7Sv7at9k273vLzZMgMaZQN3Uh15/oS+Q4SefCT8y3lrI6C0/qAZoyqsij5b11OQjHZVVVzKa5iiHggTiV4+KV34QfPskCRl+PUnzFcR1tQ2wKvY181dh4dgu7lh7tYo0cFGou2fWebRf9CyMESS9XsLeSc+HS6S7QER/NBI7KsFWIr8mJUUcMKMctdrympj3tUbFkNzt/K1FFCd/37VFsn2xsQ8yr61f2vPQvwaK72dKUUkuVaEoqSIwlDZtKyBD6xNwmAL1bMcGDqWzqjFui8oqtmbOOsaz/1K27B1kjU/91YK6HXpY6I38VzYOQlo4GibcD31f8fO6b9+j9uE5XNi8p2bWnfh2bysKT7BM91PZ/7Kx9SVcItRgginhU6SyNo2oaFUQZXOkJ3dTsq+le0vro3uL2WW78RBp542ZZJvF0tmqTJg/3d3G1Qkbi+Si5XtgMnZkOimuBRjjZTEUKtYkAR/AmYKJSGw=,iv:/HHIj8uu110A+JxcUl8tJ0CozTIWr5Q9GWtFFSF2o9g=,tag:kwea6/kJZE0BUXt/ewsiEQ==,type:str]
    key: ENC[AES256_GCM,data:RlsZTW8Fb9lK5kzjoloogxBJrxWI/IDcY/XTK6BPRwwFx9F2Ln87GZgNokDeCJtAc69KWkgRjkuaPmkx8iMiAexboc+KQ/cScQdyM6E4hjD1ytmghvh7LjYGrLxlen9MrkwWhnxbKmVzR8vZTHmpP1X10hOi8c6jQkW092mHVQ42FfF/u/clKr10Oa7+Ch73+ux6SZO5LBDwJiM11NUCjjwPLdPqKlstbIMV+WV+ggDUqpRBqZL2LaXN4p6lQsPSIdtKmuEe2Cwy9zSmND3DzJIRHeD44Rm3OE5BI7RpNV77I4HCd5ziUfp1TiDrZhKPFtjYp7c/iVSwrFmQgLAhHi5TgeyRSEi4sFBCgbCdc+2i1LT5sowZjMVeKvSifQkY,iv:WlaHw1q71aBBAzZ3siGvAWrRYllbhfz3bB/sT4sBg5Q=,tag:uSBcG+CxYXNxFTz7l/n7zQ==,type:str]
sops:
    age:
        - recipient: age1za75g4g6jl2zuq36dud2e6ssdgzj8n8ee2tnrma2jj4jeexee96sp9f4tv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySUk3cDJCcGw5SC93aW1M
            Y21reHlsT0Jrbi83ZW8vS1FyNUN3RkxlZUg0CmlnK3hSc2M4N0JyRXBpLzJ0bFRk
            cnY5ZnU1NjhGdUpqek41ekxCUkg5amcKLS0tIEg1T3ptMVlsMGZva3kzWFphNEZP
            VFc0WmZLWmswRHMzcVpvWkJ0QzlQY2cK+ge0d0l1KJKwqocPC9RWiK9XAiEHpIIG
            cE3CG4g6NWLSVDnZv6Gz8vryy8mhXfYOf8B94QLil8rBPAoLg0EtAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rcdqxlqf8v2ha2dekz7cs72ctrzh2fvqvw63w6h7e3hccvgepy0qznxa8t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Nm1sNzBndWpxQ29uSGJH
            a1Uwa0pTTG1NdjZoTjBuNjVvWCtxTlorTmlBClpnajJJNFJoL3VEQlZBY2ZKdWdm
            MmFJNnduWnc5TnA1Z2d1UnJwU0xncDQKLS0tIG1lZ2dvM1NSVVdHa3ppMjR5dTZa
            aTQzZCtlemNQK0czWVVvQVY5bTNxam8KsbowL0xCxLhLAmLVSlzYmj5Yf4x1Ui5t
            dWcqLAY8UWub0gO9GNq2jXIuHq085THlUDwFFqrOLVeCvKIuMKnMfw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dz2mx7dc3k4tlcuta6wkjf887j9uqj8gkt88czfjkulw08lz2plqc2far6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Ujc4UFI5Q0pQdkI2M3J4
            VThCNXFqQjNRaUd0OXdTbTdNOU0xOUl3VkJZCnNmS1pZeWdSLysrcHNIbEs5UXVq
            UDdub2hkY3RrV20zaG9BN0VWSEtwK0kKLS0tIGNkWHpnT2QzaE95K2NES1AxM25Y
            ZmhuV2g0RHRRakNITEdFSFpJaGxXUDAKzG9Obm1DAc0WhFWuPSEu7dOMep0qkrAT
            gxoLXiKCAmxsfo8LUC2awV95NTr9DUR1gB71PtFZNOXl2/v802n1+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rf9rplg8z4qlgq5vjj5vy558x0angagx24y4ul860gm89ezeqaes0q2ajs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZVBoR3UrZ2ZNSERtSDVp
            VWEyVnNxL3pDTStNL3QvTEhEVjlURWVvelhvCjVXRmtXUDYxOGhrYnZ0NndyZENE
            Y0phSkhhVmNEdWVKM0s5SUg0S1FYcFEKLS0tIDM1TjBndXNnUlhPdTlvaWZKN3lr
            RWwvTTJiK2RKQXdWWkZ2cjY3eDRhdHcK0w3L8blZiAeV4c4x0hqdsk7IrXvqcS00
            0loUa3SIZsyfveISC3ZxgKNmH/qONm8bpIecfvsSgc0FC05IVuJleg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kh6g0tvcks3pevyf6dz85l5zn9fkf7re9jns5j6thacrczdr9qdsqylmda
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNR3RIeXJKUjV5N0FyTmxS
            bGIvVEFOcFBQM3RzS0E4V0VNTldBQ3ZsbEVrCnhscTArUXl4NENIVWc1MHFrSGdK
            WUdlYUQ4c1FieE0wQ3EzYjN2NFYzS0kKLS0tIDg4Vi9HVVhnNFZYWTF6L0NVR0RJ
            UWloTC9JQUFCZkhDaHZ5OU1xRXQ2TzQKqhOqu8uSD9eKCQ4L8VxdzrQUtGU6KhSW
            RBbsRQzH/b92q5/jSA2GNXFVX2VkTVmNTyzXQU703UD0W/xnxu8oPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e7az94d7rpqplck2dhsrt874uu778nt8sudare4zscf2mxqlpqgsqp8up0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y0xlNEx5NXZrckhlQTRN
            ajBGdjdabTBVVjNlWnpia21Dam5ScStwbVZNCjlJZFdjM2RMQlQ1anpiV0RJVk1l
            ZWNxUUlYZ3ZkdmU1RUxvUXllM25idzQKLS0tIHd0K09lU1hmU0VINGl4Z21IZDFq
            Njh6NUI4MFhsajJqWmFOc1U4OGh4bjAKvZJEnCxr1nP2JTRW6Ov2iLuX7F2lA26K
            W4wB2Gtk068NFB+kUgUgH+5f+yBXpbvofz9lwXe37k1IWX37tZnlrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15haz8whmqr0q84aa9j2vlsrn65l5lmuyyj64pzsfw6k99cm4v49qlk4alp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeWdjb1loV3FibmpFNzlm
            Ylo4Tmt6ek1XTjNJVjY2QmJaQVZoeC9oTXdrCjBoM2xrd1FtNEhlWGNMM1BEbEpq
            RmhRMXhEU25ZdklLV3VuaUI3NGdaZ0kKLS0tIDdndFlHeCtZc1FjbXF5bnM3ZHpY
            aFJ5UFJpN3BvVUlXT2hzb0NQLytuZ2cKiMpQ/yeJYTcgj8kbfa1u8D6fvyDAiI4b
            LoANTPINTUvhN+XzCb1viHTkbK0kTSOsSUNs00ndPn5Zd88XvvBD3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T19:08:59Z"
    mac: ENC[AES256_GCM,data:1YO8hiRYjX61HjNglrQNJpCYNjKb6hYgPPJqnsH6RA49WZ5rKCbmill/2BR4pwKV4Qaa0Io52SYdg7N1F9hFIHrWroC9bTu0GIMKkC7qbGrKNcC/v/o6hRwXn2mNdcx6rydCaI/8NPhYIpWDQxvDFSQPLLM931pII+HOYfzFDjU=,iv:/mSxPUtAz2r6zJiqEAvqSfgchNn8u+lG3JRS3s9EFvg=,tag:G/fTsYSn7mARN0RWUeNdzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
