userpass:
    taylor: ENC[AES256_GCM,data:H1pUhGZ2ueasipLRfcqi+56HYnN3pq+OVWSYc22HKP1jV3Sei7v3dLEFGpxAVF/f8Mxrs7qCUriN5u1BPQfbjZVe5bSnuQ+83Q==,iv:tMxrCcQG5fJpbX3YSNteAhtftBG3YxIYqr3WwgnHf6w=,tag:GDGcFqIKPAS9LGKHy488+A==,type:str]
    sshkey: ENC[AES256_GCM,data:Eo26kowm3i/2zLjd4kfTt99E6oANn85bbHcYdhFy9Ogy7hpf8tFL8uSvfdNF0SupHnyJFHXKpRGB4Mvt1+cx6y3mltKLGVhpKnW9DNjiFF3mYbVQn0EHHfauWK4zitNPSrPgnmXX,iv:rwVZbR92mp5+3qa6M0QtXuT6IPu/kj61WMqhDURgap0=,tag:InGB4GEpq4LBZh9BEF3r2g==,type:str]
backblaze:
    keyID: ENC[AES256_GCM,data:nWkA8TpW4HK4PSWQO6bLAwnQ8dkuPYeW7g==,iv:nzBLF1H8pXrm8wsx9h+nqX3zLkStbX++Uy/QCZ1ZSMI=,tag:pzzF1GTXREwnXLf0EZwGBg==,type:str]
    applicationKey: ENC[AES256_GCM,data:B8AOGyFOAo8EUfO0B/jdPoXx9nMfQo0kBmooS4vTtA==,iv:n0jdVnHO43WDwKsoliOSrKB5Cn1i4gxlxfaS4KZU5po=,tag:E6vp/veJxHDwqx7EW5RopQ==,type:str]
    repository: ENC[AES256_GCM,data:decTk0417VDCOnNdhzYFOg6jF0gqIAzdceuHPZzZiHVKit00/uxfSlSQ+0kcsvA=,iv:KESw6Yj4oTaDZzWgrkgkA9sfoERNMr1WmQsCTXIKXEU=,tag:5VO9KKPVg0oLOnekG0+msA==,type:str]
beszel:
    sshkey: ENC[AES256_GCM,data:tRbZS0PyB1NpjMEUQ6belY2A6aYqJxlSOWt7G6CLjvjtU+RFGAM8y++5rZ+UujFA/RfQGbAfkqNYSHMmoKm4G37fUQ4YnfFWW4SwWf9ZZFc=,iv:ebOJVgYTN9CxTbHXA/VQL+G1URcRJ7+M7MgTY7PchY0=,tag:wxVzg6o6EH5Vf6YOAscO/Q==,type:str]
    hydratoken: ENC[AES256_GCM,data:GVmY5JyWaTpTBYCQ6tc1FnpD6FL+1Raf4Ljq/BSNXUQ5fpSh,iv:bWl7/M2CWPCSWdJTTfezf9GWVo34gyX9/nAZZVjJ1fk=,tag:qVNBA8rN1q8/Kp8l8FsTtw==,type:str]
    dns01token: ENC[AES256_GCM,data:6rUUMmDlzKvI4S1siLbGNK+oS6Zm3LS0L6foSb5cN7SpaUqN,iv:dZFQCYJg/57GMiIdba+PgN3sCQ2tm724F7RK+rqLtaQ=,tag:ZELw4T5j4dXXc7VapEfrQw==,type:str]
    incustoken: ENC[AES256_GCM,data:MZt7yY/kdF2Zk3MHUPTLzzn3T4AsRsn3RcJ2DLGeHTZaW96D,iv:cok45iTmURVv2S4RuxGJv+L8lup36EPrzqvCI5+LN74=,tag:mcI56oWYlrHGX4PJZt+QOA==,type:str]
    argontoken: ENC[AES256_GCM,data:9QBs33nyXOE6Zp29Nm2jTLtxrPyhoKlWx423UlxGa5hw2dGJ,iv:N+GtTOympw68vhFlsLjHrvGpPXarZ95YSBmtyKDuXZo=,tag:WDIFZjsjm67jiRMs6/RUQQ==,type:str]
cachemover:
    pass: ENC[AES256_GCM,data:FlbW7HtnAQ==,iv:wb/Z7P8I0bCWNAEf/6ikkkHY3DHhEL0egXtFoYU9mv4=,tag:V5Ke+B/M51ofLkvy3qZw6A==,type:str]
    healthchecks: ENC[AES256_GCM,data:WjtrzBS1tFiyMDc+2atLqIDbyITLU7WKm8fZOWY77KUgMvqxJ6BCxF0kz+Jzhg0sKbjKFQtS2RALyfmjde0fFwLFTxQ5EEixZw==,iv:AZMWqMfYTg22vRg9YgVav4lQB4AtkRzKFRqtHUmYkaI=,tag:o5U2k3mBriZHmNQE64bDlg==,type:str]
    apikey: ENC[AES256_GCM,data:g9P24ZZs3mVyTsVTWKVpOqw9Tnw+XzJsKq05nw7gsZ/eYSMtzsH+Qvh5pIt97BxE8r19+3m6+S9PpMMZROyCwg==,iv:tc229JH+LsPn4REJ4syWtdSGFjRDCMJHFaoP5PMMVWI=,tag:ly+reSlunw+1t/b3e+35xg==,type:str]
    discordurl: ENC[AES256_GCM,data:8XIMrZw0jJ7trUrN8DVLkomn4sXA23pLlFIQQr1MDXYl53utV691Bj/WleIZU58mMuRhSIfqhIj3Qa0A4/Eg7rCbpGzFZuLTS4TbpoM0TEWaM3URF+rpgRN+o3uRrvQiTZQ=,iv:ODth9BBMRjdTiPl++FsnSwWCwMkTT31zSSNDQbMRCWo=,tag:Nb9Qdp9v1QpAF6uBvIzBtg==,type:str]
rclone:
    client_id: ENC[AES256_GCM,data:ZgRk+WfV0tmAugRfJbLY06VBUadZ9ek9CObb9VL04US5Vs116eUMlXgx9izcQjTw87D6g9XDGNhbD8guC3pKeRoQCeSqfNlr,iv:xd+PMEGoxMZRZtzVkVVdJMpR1SnJijnmg3RaAeeRDvE=,tag:cRSOL/YEmpsJwZU5bry92g==,type:str]
    client_secret: ENC[AES256_GCM,data:pWwBDsBnjNtnhuhxApjePNEybPRIf0PYHccj0vBYQ661VBU=,iv:8228IY5x0TY/aUdrYvadgytuVpa360RI31do5WVdr3I=,tag:DF8oQo5KDU8T66tYFiO8rQ==,type:str]
    token: ENC[AES256_GCM,data:qxVrkUt8NKwHB5CYA3xFIkXamG53BkI7sNAGAnwss66JzTTxbHR4xeiN0uW1rnZafHLkSHeop+wdK6I2Gk1KFtMUx/7UvXKIkKALMH+zmeEBY3TjyuaWP64elCHgH0Uz18epQlUjDYkYxIOvE3tFPbTgWVbEr8ywkEw8tSVWI+e924l+/oH68oueefeK8FcMvOg2E2F6cAYGRo1WnW/yodlkZSCc0/x7EtUvBmyUCPy58YTg+baic7qpCrFSl/0/4GfjN8VWbsg4nysX/POKHyGfAeeGPMThPdNcpdZka6owwDVDQarxNN7jz2GsR8g1xekycR8+Q6i1CIueKF4NN2hntSeYqohR9dfLrKkJFa5EqV5USzptoWNmyMnkNCPoYfZyViIQDbAQFbIHIo06bR8Lk7koMzYNVZxwdHRiuyYXOF9VhQ+ssIO/hAZgAE7cGY7o8c7uphFUbn9TlRi0pZW760jZtB21FHElJSjTpfIlN3xvDlMZpefg4Uv0zNO3Xb/FDp0JEjnRXueYeX10PKj0PGcS0L3mN4FKAiafU/40/7YjnnOVrcsfcdAP1VR+,iv:rxLfOqioXG6Ny8KszGe4Ws0cgn0WP+wjR2tKUH0BoEU=,tag:GMuaQ9uZvKpcL6g42HKX6Q==,type:str]
restic:
    repokey: ENC[AES256_GCM,data:CEgwLBYiMLBoi6OZBXlzfe2G3UUzopC5fCuzjuFUgyE=,iv:BsTRwxGExpG8i/cahNMLBuG4CfnrdZLlghv5hUwlSFI=,tag:/8OEUi84KXIwpSod8RhKDg==,type:str]
snapraid:
    healthchecks: ENC[AES256_GCM,data:lZVlP2JkRUnV+Q1Xx8MpnvOptrWayYGYlL0PfSqvt0OxGue5TxOus6nr9OVbtzcK9W9oTiWanZcYhTRRx1c3x7wtbU3YVV9bQQ==,iv:pUxJJuzCxlbQi6OzJLYLCn4M3pO7GfErwjJgboqRIlw=,tag:Rro2FGI1BZhPUiSxDHU5iA==,type:str]
act-runner:
    token: ENC[AES256_GCM,data:hOtIYzjj0wNXtT9URlQnyhGXnGCrjuCNf2AwbWvE/vOtZujPNg2D2v2IQ85q4g==,iv:JJlo2AGoTjZU3n/RyraK/utZ20dCKAMuP87RZEBbD4k=,tag:MYwCR+EpYByunOH1NN2Obg==,type:str]
renovate:
    github_key: ENC[AES256_GCM,data:qZ2Yp/DGH8A1TuncbMVMf2B0xoIyBpGJ55qppkEykY62enzworZ2lx9XE7LAr07QIBMJuyhgtKqqR3CpLoWoMuXu/2oGI/Z+oy9ki7YGFDiBq/CYb5gQEkZJcxny,iv:NM3nrXKLoWCsf+AKJYy01pBsFIjgD6uv1ZhyjPLp3yE=,tag:DuiA16V42ycnuxGkqwMQZA==,type:str]
    renovate_key: ENC[AES256_GCM,data:pfeZewpUCdprwUUe9FMLa7eF7ogjIUnJzqYjOfjKIcPujyljQr1TuA==,iv:PMLrHqkqG9xXQf5fUbErZ9dQDvgbyuFxQVRFGGB/wKg=,tag:CteXVdmvKHB3FvUPuKinFw==,type:str]
ups:
    notifyurl: ENC[AES256_GCM,data:hqVwUwGbCe+sXdjcmmEY2MRb9rs42boS9vaiZnlc/VM1bEwjH4OqpqZzh1uDhCNJohhQW27sHiWLZhoe7r80bvWgIwtrpZT5SzwNzHJYpQOznZmHshVpMqbEj9AaX0s77zsFfJLaydvhxVqzt2MjuBNG44hPv55mYA==,iv:Z209zesFABBmloir6SSjsEZmBSjAQIzy4eNvvdkEezc=,tag:t1iiiLQrkpNtyhTR2Ufjow==,type:str]
    adminpass: ENC[AES256_GCM,data:pmxtJUjWpqmDcRZdpPjSxhrqlU482HX4yjE=,iv:9FbgFyNNKWdgOOQUQOpbSoOl+c8A79FIzAvgzHLNPZA=,tag:g0Ku0DckGWKuSJ2EcBDmZw==,type:str]
    guestpass: ENC[AES256_GCM,data:xUJWj4x6M7Tu2C8otqqXoxWflg==,iv:qjrUotXSqe6bkf1QNlEAWRuwf6cf866KI46LDHu9x40=,tag:hDG5nos0HBPNGh9UgJZJTA==,type:str]
syncthing:
    cert: ENC[AES256_GCM,data:+Fg1BRCX+fxm3XX82ZuKq+7J2IGLWVTqc5jFlJJsvxPetRf+D2tKL/sbzVHXPh78QT5VkBYk9gsodXd5yOTLv6q0JF1UdEGqs/mCtnR1taPMgmG6p8hgoSah7kvBvDWZQZ/lNcnlNU2MbFvG1WLVxb97tWqYrBwAObVGxAvDITKgEFHNizIucQuYyUax6Fsa/8L3kVzaG+ijpcstZQJY4sNamngRWzK3XxXV8YkAsBiU8epIuMQH26rOn4b44lEv65/7yR5VeJyQMh5+RfH/nC7ICS2ShYOhxhrRkBhRtBlcS7QLXokVxF+9GV95CiOb2CgQuU/ZB6PGO71EdcUEMgH0NUAeF4lQcuUyE/daHZcH4UcBmNNJyTsOpe1lUuwObk2+KAmLh2IVMzZGy6DRlu4RGZmoUxvGin3veXwyHotKrUK69QStKmU2ca7YLYURBOju45t9YtbB2mFYGQGor/C79SHzKth1e/AXuJPhofBusxXla052bAVS1nOQBv1xQoC8ynC9EJJ9h9dPZYsCR5n0iTZEjGkp0bn1eB95nFvY/wh+hvRg7ckHVFuzOJSI7Sv7at9k273vLzZMgMaZQN3Uh15/oS+Q4SefCT8y3lrI6C0/qAZoyqsij5b11OQjHZVVVzKa5iiHggTiV4+KV34QfPskCRl+PUnzFcR1tQ2wKvY181dh4dgu7lh7tYo0cFGou2fWebRf9CyMESS9XsLeSc+HS6S7QER/NBI7KsFWIr8mJUUcMKMctdrympj3tUbFkNzt/K1FFCd/37VFsn2xsQ8yr61f2vPQvwaK72dKUUkuVaEoqSIwlDZtKyBD6xNwmAL1bMcGDqWzqjFui8oqtmbOOsaz/1K27B1kjU/91YK6HXpY6I38VzYOQlo4GibcD31f8fO6b9+j9uE5XNi8p2bWnfh2bysKT7BM91PZ/7Kx9SVcItRgginhU6SyNo2oaFUQZXOkJ3dTsq+le0vro3uL2WW78RBp542ZZJvF0tmqTJg/3d3G1Qkbi+Si5XtgMnZkOimuBRjjZTEUKtYkAR/AmYKJSGw=,iv:/HHIj8uu110A+JxcUl8tJ0CozTIWr5Q9GWtFFSF2o9g=,tag:kwea6/kJZE0BUXt/ewsiEQ==,type:str]
    key: ENC[AES256_GCM,data:RlsZTW8Fb9lK5kzjoloogxBJrxWI/IDcY/XTK6BPRwwFx9F2Ln87GZgNokDeCJtAc69KWkgRjkuaPmkx8iMiAexboc+KQ/cScQdyM6E4hjD1ytmghvh7LjYGrLxlen9MrkwWhnxbKmVzR8vZTHmpP1X10hOi8c6jQkW092mHVQ42FfF/u/clKr10Oa7+Ch73+ux6SZO5LBDwJiM11NUCjjwPLdPqKlstbIMV+WV+ggDUqpRBqZL2LaXN4p6lQsPSIdtKmuEe2Cwy9zSmND3DzJIRHeD44Rm3OE5BI7RpNV77I4HCd5ziUfp1TiDrZhKPFtjYp7c/iVSwrFmQgLAhHi5TgeyRSEi4sFBCgbCdc+2i1LT5sowZjMVeKvSifQkY,iv:WlaHw1q71aBBAzZ3siGvAWrRYllbhfz3bB/sT4sBg5Q=,tag:uSBcG+CxYXNxFTz7l/n7zQ==,type:str]
sops:
    age:
        - recipient: age1za75g4g6jl2zuq36dud2e6ssdgzj8n8ee2tnrma2jj4jeexee96sp9f4tv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWkE4UlpDMzNNQ2JQTm01
            aWlNYklYc1lGODd0MGhRZ25uL3ZkY2hyUEh3CmtpNFhaeUJsR254L2tmTFVqVUs0
            SDNMVy9ZWHA1RC83UFl3MDNSV3VneG8KLS0tIGJpOGxqdExCWm9BSThrd1NMZU1o
            b1RVMDF5WklGYTA0TkdPSHVieE5KYTQKYfAgcFMXT4SrSRdZRcyfl7WTg7mSAQWg
            xvnNsAOUmaVYgd4X3vJHLu3whYZw8St6VUFl/QXoy6u/jkDcSHh9QA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rcdqxlqf8v2ha2dekz7cs72ctrzh2fvqvw63w6h7e3hccvgepy0qznxa8t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOei9RRHJKbFpQbmdJWnlk
            Y3FyZEQxeUJqRVRYb3lBWkg3SHB3MjlBWml3Ckl3MVhBSCtyelh1KzBLbjR4bmFB
            ZDk5WHlFOW05VzFTdDZHU3Y1NkpVdUEKLS0tIGM2blhSVW9nYVExcEQwQVpVQWVU
            MXYzemROckh5aXNsdTYwTG5hUUJmU1EK8wK9TNnACGlsz3dhY/wpcsv7+XkfiELR
            ai3N6PhXJ5o++1xS1yvIz2GLTqGIMSM0UZ5TZGnA2RUnCBtLFEiCSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dz2mx7dc3k4tlcuta6wkjf887j9uqj8gkt88czfjkulw08lz2plqc2far6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMktLRUNPNnpXeHFVUUhv
            ektGNkttd1UyMFN4WUdMZGFKSU5HUitkVjNFCjZBVEpjZENMeEJRL3hHVFFvVWdk
            OEQyVE56Q2NzK1B2SWlncWhxeENHaFEKLS0tIGkvR2UyMWtNNGl3ZkNzNEFwTjZK
            b29iV3ZaOEgxaU9KN3NPQ0RBWE5aK28Kdiyv52JAqm8MPaLck9hYnODsfYI1OJR7
            91xtmAa6KVLogF/jzbnAHtsYyqJwZrdUjbuRZzg5TLYu37miiP83xg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rf9rplg8z4qlgq5vjj5vy558x0angagx24y4ul860gm89ezeqaes0q2ajs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUjlVNWlkdEkrUEVIcnVT
            OUxSbzd1a0I3V3RBRFA4aTNVMzBMYURsc1ZFCi9Ua3QwbTBuMHA1bGVwS0gvR1pM
            SXlUSVFjWEFKYklKbjZZSnhCWnZZZTgKLS0tIFM4YW5BdytBVlFvUm1pRFFlNDN0
            UVpSamI3UU1XTEVGa2prNmFnT2l6VFUKkfGjISIOb55kD0We7HpQNNylFzkj5dik
            nQYb42stHng3ndAo1Wffv3Wnq/NEKveOA6GF9sMLO1equ3sX6mXz1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sr90fdh608d8kxpcujmuddxxlc4f0uk4l7ur4mkxsaxw3dyun90sv2q9ca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRjZkR3lPakxFMmlicEVT
            dWFCVTlvL0hPSk1vMHFwKzFjeDZTY0ppM0VNCnZ3ckNmSkhhc3BQcTZTQW1YOXk0
            d1k5b3J0dkN5c2FGQzFJWmN3YWFZWjAKLS0tIGloMDV5Ri9iNmhVaHNQK3FCZFlu
            Ynp2T1kzYnFBRVptSGhtZGR2cWVKTzAKCowSlCJWqwuJUKpQxEySWCObL09xOafY
            XKE13damhyzC5kf+jq7eq4j82GyCmCdRFJCNQzL858wYNBJT50/4Hw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s82lfezym83mqpyw3yvqlrasrf6qagdhm3sfqr3m4lscttujfg7strmhhk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY3ZnT2RGamJkNEw1MTNP
            ZDdZSGFjMjlHa3VIUER1eEhCaGdjVFRmVEZJCldmZnV0eXMvKzFqeFFKOTZyWmVt
            OWZkUkU4Y1czS01PZ2dUeWdwWTFaM00KLS0tIEs2anNkYUdFcmYxNjRveHh3TUlN
            VVNVclI5LzVTTXdtYmc3U3RMa3R4WE0KM/oZux1oHe2Z8jxFiwypZaDWgRtUvznP
            VQ2MEicm4uaUb6V4Y1kWP6tXHZi5mpZHR/wcQYe102q5cbfU6J48Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T02:59:57Z"
    mac: ENC[AES256_GCM,data:0GH17nLTh868bBHtIvnV7WuhkYrPVW9v+WvZz7MwuyM66KM0dG0+BbhaE3sFIs1ZitWcJF5n/BHWnJhtTSyeYGJOHjVxN954ZVWd/q7BDaMZaw1+0nf/Qe6WSJ7oeiqsGxvbjNBj4dmVD4u5jCKZMybGbxoTcne5XoZCz+BVFkc=,iv:Q1XZQDt2KdLYKFiMPYvFsRpGLrYVaCd7v69triVjKoE=,tag:V6wJbkT9iTUAtR3RXmU2VQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
